from typing import List

def add_cpu(a: List[float], b: List[float]) -> List[float]: ...
def add_gpu(a: List[float], b: List[float]) -> List[float]: ...
def dot_cpu(a: List[float], b: List[float]) -> List[float]: ...
def dot_gpu(a: List[float], b: List[float]) -> List[float]: ...
